# functions

In [ ]:
# set of code ,which once created, they can be used throughout the program
# --> help to break our program into smaller parts
# --> help to look more organized and manageable

In [ ]:
def hello():
  print("hello me !")
hello()

hello me !


In [ ]:
def add():
  x=12
  y=234
  print(x+y)
add()

246


In [ ]:
# parameters
# --> are the variables written inside the parentheses with the name of function
# arguments
# --> values passed to the parameters while call the function

In [ ]:
def add(x,y):# parameters
  print(x+y)
add(11,24)# arguments

35


In [ ]:
def rect(lenght,width):
  print("the area of rectangle is :",lenght*width)
rect(2,3)

the area of rectangle is : 6


In [ ]:
# arbitory arguments
def hello(*name):
  print("hello , my name is ",name[1])

hello('lisa','jon')

hello , my name is  jon


In [ ]:
# return and recursion
# return --> exit a function

In [ ]:
def hello ():
  return ("hello me !")
print(hello())

hello me !


In [ ]:
# recursion --> function can call itself

In [ ]:
def hello():
  print("hello")
  return(hello())
print(hello())

In [ ]:
# factorial
def fac(n):
  if n==1:
    return 1
  else:
    return n*fac(n-1)
print(fac(5))

120


# lambda

In [ ]:
# --> requied short period of time
# --> take numerous arguments
# --> have one experssion

In [ ]:
a=lambda x,y:x+y
print(a(1,2))

3


In [ ]:
a=lambda b:b*4
print(a(4))

16


In [ ]:
x=lambda a,b,c:(a+b)*c
print(x(2,6,4))

12


In [ ]:
# local variables
# --> restricted to only one block or code
# --> cannot be changed throughout the program
# global variables
# --> not restricted to one block of code
# --> can be changed throughout the program


In [ ]:
x=23
print(x)
def hello():
  x=25
  return x
print(hello())
print(x)

23
25
23


In [ ]:
x=23
print(x)
def hello():
  global x
  x=25
  return x
print(hello())
print(x)

23
25
25


# **problems**

**write a program to find max of three number in python**

In [ ]:
def max(val1,val2,val3):
  if val1>val2 and val1>val3:
    return val1
  elif val2>val1 and val2>val3:
    return val2
  else:
    return val3
print(max(1,7,3))

7


**write a python function to create and print a list where the values are square of number between 1 to 30**

In [ ]:
def create_list():
  list=[]
  for i in range(1,31):
    list.append(i**2)
  return list
print(create_list())

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900]


**write a python function that takes a number as a parameter and check if the number is prime or not**

In [ ]:
def check_prime(num):
  if num==1:
    return False
  for i in range(2,num):
    if num%i==0:
      return False
  return True
print(check_prime(2))

True


**write a python function to sum all the numbers in a list**

In [ ]:
def add (num):
  sum=0
  for i in num:
    sum+=i
  return sum
print(add([1,2,3,4,5]))
# using recursion
def add(num):
  if len(num)==0:
    return 0
  else:
    return num[0]+add(num[1:])
print(add([1,2,3,4,5]))

15
15


**write a python program to solve the fibonacci sequence using recursion**

In [ ]:
def fibonacci(num):
  if num==1:
    return 0
  elif num==2:
    return 1
  else:
    return fibonacci(num-1)+fibonacci(num-2)
print(fibonacci(7))



8


# modules

In [ ]:
# modules  are the .py files
# 200 to above modules in python we have

In [ ]:
# --> in bulit modules

In [ ]:
# date time
import datetime
x =datetime.datetime.now()
print(x)
y=datetime.datetime(2022,12,31)
print(y.strftime("%A"))
print(y.strftime("%a"))
print(y.strftime("%m"))
print(y.strftime("%y"))

2025-04-15 17:23:27.438299
Saturday
Sat
12
22


In [ ]:
# random
import random
print(random.randint(1,10)) # random integer
print(random.random()) # random float
l=["head","tail"]
print(random.choice(l)) # random choice
random.shuffle(l) # shuffle
print(l)

3
0.9347277713796097
tail
['head', 'tail']


In [ ]:
#  math
import math
x=max(23,45,62,12)
print(x)
y=min(23,45,62,12)
print(y)
z=abs(-23) # absulute convert - to positive
print(z)
a=pow(2,3)
print(a)
b=math.sqrt(25)
print(b)
c=math.ceil(2.3)
print(c)
d=math.floor(2.3)
print(d)

62
12
23
8
5.0
3
2


# numpy

In [ ]:
# numpy short form of Numerical python
# defnes a multi-dimention arry


In [ ]:
import numpy as  np


In [ ]:
l1 =[20,30,40,50]
l2=[30,40,50,60,70]
l3=5
print(l1+l2)
print(l1*l3)

[20, 30, 40, 50, 30, 40, 50, 60, 70]
[20, 30, 40, 50, 20, 30, 40, 50, 20, 30, 40, 50, 20, 30, 40, 50, 20, 30, 40, 50]


In [ ]:
a=np.array([20,30,40])
b=np.array([40,50,60])
print(a)
print(b)
print(a+b)
print(a*b)

[20 30 40]
[40 50 60]
[ 60  80 100]
[ 800 1500 2400]


In [ ]:
a=np.array([30,40,"39"])
print(a)

['30' '40' '39']


In [ ]:
l1=np.array([[1,2,3],[4,5,6]])
print(l1)

[[1 2 3]
 [4 5 6]]


In [ ]:


arra=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arra)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:


arr=np.array([20,30,40])
print(arr[1])
print(arr[:3])

30
[20 30 40]


In [ ]:
arr=np.array([[20,30,40],[50,60,70]])
print(arr[:2,:3])
print(arr[0,1:]) # 0 array
print(arr[1,1:]) # 1 array
print( )

[[20 30 40]
 [50 60 70]]
[30 40]
[60 70]



In [ ]:
arr=np.array([[20,30,40],[50,60,70],[20,30,40]])
print(arr[2,1:])
print(np.shape(arr)) # rows and coloum
print(len(arr)) # no of nested value
print(np.size(arr)) # total number of element in an array
print(np.ndim(arr)) #
print(arr.dtype)
print(arr.itemsize)
# a.astype(int) --> convert on array to a different data type
print(arr.astype(float))

[30 40]
(3, 3)
3
9
2
int64
8
[[20. 30. 40.]
 [50. 60. 70.]
 [20. 30. 40.]]


**mathematical operations and functions**

In [ ]:
arr=np.array([10,20,30,40,50])
arr1=np.array([60,70,80,90,10])
print(np.add(arr,arr1))
print(np.subtract(arr,arr1))
print(np.multiply(arr,arr1))
print(np.divide(arr,arr1))
print(np.mod(arr,arr1))


[ 70  90 110 130  60]
[-50 -50 -50 -50  40]
[ 600 1400 2400 3600  500]
[0.16666667 0.28571429 0.375      0.44444444 5.        ]
[10 20 30 40  0]


In [ ]:
arr=np.array([[10,20],[40,50]])
arr1=np.array([[60,70],[90,10]])
print(np.add(arr,arr1))
print(np.subtract(arr,arr1))
print(np.multiply(arr,arr1))
print(np.divide(arr,arr1))
print(np.mod(arr,arr1))

[[ 70  90]
 [130  60]]
[[-50 -50]
 [-50  40]]
[[ 600 1400]
 [3600  500]]
[[0.16666667 0.28571429]
 [0.44444444 5.        ]]
[[10 20]
 [40  0]]


In [ ]:
# power
arr1=np.array([20,30,40,])
arr2=np.array([2])
print(np.power(arr1,arr2))

[ 400  900 1600]


In [ ]:
arr1=np.array([400,900,1600])
print(np.sqrt(arr1))
print(arr.dtype)


[20. 30. 40.]
int64


**Combinig and split array**

In [ ]:
# concatination
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80,90])
print(np.concatenate((arr1,arr2)))



[10 20 30 40 50 60 70 80 90]


In [ ]:
arr1=np.array([[10,20,30],[40,50,60]])
arr2=np.array([[60,70,80],[90,10,20]])
print(np.concatenate((arr1,arr2),axis=1))
print(np.concatenate((arr1,arr2),axis=0))

[[10 20 30 60 70 80]
 [40 50 60 90 10 20]]
[[10 20 30]
 [40 50 60]
 [60 70 80]
 [90 10 20]]


In [ ]:
print(np.hstack((arr1,arr2))) # hotizontal concatenation

[[10 20 30 60 70 80]
 [40 50 60 90 10 20]]


In [ ]:
print(np.vstack((arr1,arr2))) # vertical concatenation

[[10 20 30]
 [40 50 60]
 [60 70 80]
 [90 10 20]]


In [ ]:
# split
arr=np.array([10,20,30,40,50,60])
print(np.array_split(arr,5))

[array([10, 20]), array([30]), array([40]), array([50]), array([60])]


**addition and emove in array**

In [ ]:
# np.append
# if data in 2d convert it in 1d and append it
a=np.array([10,20,30])
b=np.array([40,50,60])
print(np.append(a,[23,45,56]))
print(np.append(a,b))

[10 20 30 23 45 56]
[10 20 30 40 50 60]


In [ ]:
print(np.insert(a,2,23))

[10 20 23 30]


In [ ]:
a=np.array([[10,20,30],[40,50,60]])
print(np.insert(a,(2,3),[30,50],axis=1))
print(np.insert(a,1,[50],axis=0))

[[10 20 30 30 50]
 [40 50 30 60 50]]
[[10 20 30]
 [50 50 50]
 [40 50 60]]


In [ ]:
print(np.insert(a,(2,3),[30,50],axis=1))
print(np.insert(a,[1,2],[50],axis=0))
print(np.insert(a,[1,2],[50],axis=1))

[[10 20 30 30 50]
 [40 50 30 60 50]]
[[10 20 30]
 [50 50 50]
 [40 50 60]
 [50 50 50]]
[[10 50 20 50 30]
 [40 50 50 50 60]]


In [ ]:
a=np.array([[10,20,30],[40,50,60]])
print(np.delete(a,1,axis=0))
print(np.delete(a,1,axis=1))

[[10 20 30]]
[[10 30]
 [40 60]]


In [ ]:
# short
ar=np.array([[2,3,4,1,23,5],[2,7,5,34,56,2]])
print(np.sort(ar))

[[ 1  2  3  4  5 23]
 [ 2  2  5  7 34 56]]


In [ ]:
# filter

arr=np.array([20,30,40,50])
# fa=[True,False,True,False]
# print(arr[fa]) # gives only true value
# fa=arr>35
fa=arr%2==0
print(arr[fa])

[20 30 40 50]


In [ ]:
# search
ar=np.array([2,3,4,1,23,5])
print(np.where(ar==2))
print(np.where(ar%2==0))
ar=np.array([3,4,5,2,1])
print(np.searchsorted(ar,3))

(array([0]),)
(array([0, 2]),)
0


**aggregating function**

In [ ]:
a=np.array([20,30,40,50])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a)) # give us count
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.cumsum(a))
print(np.cumprod(a))

140
20
50
4
35.0
35.0
11.180339887498949
125.0
[ 20  50  90 140]
[     20     600   24000 1200000]


In [ ]:
a=[100,150,199,200,250,130]
b=[10,50,30,40,30,10]
price=np.array(a)
quantity=np.array(b)
print(price,"\n",quantity)
c=np.cumprod([price,quantity], axis=0)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
31270


In [ ]:
# statistical functions
baked_food=[200,250,150,190,200,280]
a=np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food)) # central value after sorting


211.66666666666666
200.0


In [ ]:
# mostly occire values use statistic lab
import statistics as stats
print(stats.mode(baked_food)) # re occuring value
print(np.std(baked_food))
print(np.var(baked_food)) #squre of std

200
42.19662967057388
1780.5555555555557


In [ ]:
# -1  represent inversely proporational relationship
# +1  represent proporational relationship
#  = mean no relationship
tobacoo_consumtion=[30,50,10,30,50,40]
deaths=[100,120,70,100,120,112]
print(np.corrcoef(tobacoo_consumtion,deaths))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [ ]:
price=[300,100,350,150,200]
sales=[10,20,7,17,3]
print(np.corrcoef(price,sales))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
